---
spring:
        profiles: adjective
        application:
                name: eureka-client${spring.profiles.active}            
words: reasonable,leaky,suspicious,ordinary,unlikely
eureka:
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/
---
spring:
        profiles: article
        application:
                name: eureka-client${spring.profiles.active}        
words: a,the
eureka:
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/
---
spring:
        profiles: noun
        application:
                name: eureka-client${spring.profiles.active}        
words: boat,book,vote,seat,backpack,partition,groundhog
eureka:
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/
---
spring:
        profiles: subject
        application:
                name: eureka-client${spring.profiles.active}        
words: I,You,He,She,It
eureka:
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/
---
spring:
        profiles: verbs
        application:
                name: eureka-client${spring.profiles.active}        
words: ran,knew,had,saw,bought
eureka:
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/