---
spring:
        profiles: eureka-client-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
eureka:
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/
---
spring:
        profiles: eureka-client-article
words: a,the
eureka:
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/
---
spring:
        profiles: eureka-client-noun
words: boat,book,vote,seat,backpack,partition,groundhog
eureka:
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/
---
spring:
        profiles: eureka-client-subject
words: I,You,He,She,It
eureka:
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/
---
spring:
        profiles: eureka-client-verbs
words: ran,knew,had,saw,bought
eureka:
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/