---
spring:
        profiles: adjective
        application:
                name: eureka-client-${spring.profiles.active}
words: reasonable,leaky,suspicious,ordinary,unlikely
eureka:
        instance: 
                instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
---
spring:
        profiles: article
        application:
                name: eureka-client-${spring.profiles.active}
words: a,the
eureka:
        instance: 
                instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
---
spring:
        profiles: noun
        application:
                name: eureka-client-${spring.profiles.active}
words: boat,book,vote,seat,backpack,partition,groundhog
eureka:
        instance: 
                instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
---
spring:
        profiles: subject
        application:
                name: eureka-client-${spring.profiles.active}
words: I,You,He,She,It
eureka:
        instance: 
                instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
---
spring:
        profiles: verbs
        application:
                name: eureka-client-${spring.profiles.active}       
words: ran,knew,had,saw,bought
eureka:
        instance: 
                instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
        client:
                serviceUrl:
                        defaultZone: http://localhost:8010/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/